/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'mains' : IDL.Null,
  'desserts' : IDL.Null,
  'starters' : IDL.Null,
  'snacks' : IDL.Null,
  'drinks' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'isVeg' : IDL.Bool,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addMenuItem' : IDL.Func([MenuItem], [IDL.Nat], []),
  'getAllItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getItemsByCategory' : IDL.Func([Category], [IDL.Vec(MenuItem)], ['query']),
  'getMenuItem' : IDL.Func([IDL.Nat], [MenuItem], ['query']),
  'searchByName' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'mains' : IDL.Null,
    'desserts' : IDL.Null,
    'starters' : IDL.Null,
    'snacks' : IDL.Null,
    'drinks' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'isVeg' : IDL.Bool,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addMenuItem' : IDL.Func([MenuItem], [IDL.Nat], []),
    'getAllItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getItemsByCategory' : IDL.Func([Category], [IDL.Vec(MenuItem)], ['query']),
    'getMenuItem' : IDL.Func([IDL.Nat], [MenuItem], ['query']),
    'searchByName' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };